config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord

  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true, numericality: { only_integer: true }
  validates :number_of_guests, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show]
  def index
    @flats = Flat.all
  end

  def show
  end

  def create
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>

<div class="grid-container">
  <% @flats.each do |f| %>
    <div class="flat-card card">

      <img src="https://source.unsplash.com/random" alt="flat photo">

      <div class="flat-card-footer">
        <div class="flat-details">
           <h3><%= f.name %></h3>
           <p><% f.description %></p>
           <div class="icons">
             <p><i class="fas fa-male"></i> <%= f.number_of_guests %></p>
             <p><i class="fas fa-dollar-sign"></i> <%= f.price_per_night %></p>
           </div>
        </div>

        <div class="flat-actions">
          <div class="action-ink">
            <%= link_to 'More info', flat_path(f) %>
          </div>
          <div class="action-link">
            <%= link_to 'Edit', edit_flat_path(f) %>
          </div>
          <div class="action-link">
            <%= link_to 'Remove', flat_path(f),  method: :delete, data: { confirm: "Are you sure you want to delete '#{f.name}'?" } %>
          </div>


        </div>
      </div>

    </div>
  <% end %>
</div>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Flats', flats_path %>

      <!-- add flat -->
      <%= link_to 'Add flat', new_flat_path, class: 'btn btn-success' %>

    </nav>
    <%= yield %>
  </body>
</html>